# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ncVB3I2RcnPHczVwRR-UNUs4aok03gU
"""

import streamlit as st
from datetime import datetime

st.set_page_config(page_title="Cierre de Caja", page_icon="💰", layout="centered")

st.markdown("""
    <style>
        .stApp { max-width: 500px; margin: 0 auto; background-color: #ffffff; border-radius: 20px; padding: 20px; box-shadow: 0 0 15px rgba(0,0,0,0.1); }
        h1 { text-align: center; color: #2c3e50; }
        .footer { text-align: center; font-size: 0.8rem; color: #7f8c8d; margin-top: 30px; }
    </style>
""", unsafe_allow_html=True)

st.title("💰 Cierre de Caja")
st.caption(f"📅 {datetime.now().strftime('%d/%m/%Y %H:%M')}")

with st.expander("🏪 Cierre de Caja Local", expanded=True):
    col1, col2 = st.columns(2)
    with col1:
        com_fisicas = st.number_input("Comandas físicas", value=0.0, step=0.01)
        caja_ini = st.number_input("Caja inicial", value=0.0, step=0.01)
        efectivo_cont = st.number_input("Efectivo contado", value=0.0, step=0.01)
        depositos = st.number_input("Depósitos", value=0.0, step=0.01)
    with col2:
        pos = st.number_input("POS", value=0.0, step=0.01)
        salidas = st.number_input("Salidas de dinero", value=0.0, step=0.01)

    ventas_efectivo = com_fisicas - pos
    efectivo_ideal = ventas_efectivo + caja_ini - salidas
    diferencia = efectivo_cont - efectivo_ideal
    estado_final_caja = efectivo_cont - depositos

    st.markdown("### 📊 Resultados")
    col_r1, col_r2 = st.columns(2)
    with col_r1:
        st.metric("Ventas en efectivo", f"{ventas_efectivo:,.2f}")
        st.metric("Efectivo final (ideal)", f"{efectivo_ideal:,.2f}")
    with col_r2:
        st.metric("Diferencia", f"{diferencia:,.2f}", delta_color="inverse")
        st.metric("Estado final en caja", f"{estado_final_caja:,.2f}")

with st.expander("💳 Cierre de Caja Total", expanded=True):
    col3, col4 = st.columns(2)
    with col3:
        pos_ventas = st.number_input("POS y ventas efectivo", value=0.0, step=0.01, key="pos_total")
        fondo_ini = st.number_input("Fondo inicial", value=0.0, step=0.01)
        caja_contada = st.number_input("Caja contada (real)", value=0.0, step=0.01)
        depositos_total = st.number_input("Depósitos", value=0.0, step=0.01, key="dep_total")
    with col4:
        salidas_total = st.number_input("Salidas totales", value=0.0, step=0.01)
        pedidos_ya = st.number_input("Pedidos Ya", value=0.0, step=0.01)

    ventas_totales = pos_ventas + pedidos_ya
    caja_ideal = pos_ventas + fondo_ini + pedidos_ya - salidas_total
    diferencia_total = caja_contada - caja_ideal
    estado_cuentas = caja_contada - depositos_total

    st.markdown("### 📊 Resultados")
    col_r3, col_r4 = st.columns(2)
    with col_r3:
        st.metric("Ventas totales", f"{ventas_totales:,.2f}")
        st.metric("Caja ideal", f"{caja_ideal:,.2f}")
    with col_r4:
        st.metric("Diferencia", f"{diferencia_total:,.2f}", delta_color="inverse")
        st.metric("Estado final cuentas", f"{estado_cuentas:,.2f}")

st.markdown("---")
st.markdown('<div class="footer">✅ Datos en tiempo real - Cierre de caja</div>', unsafe_allow_html=True)